name: cn domain list

on:
  schedule:
    - cron: "0 0 * * 5"
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Clone v2fly/domain-list-community
        run: git clone --depth=1 https://github.com/v2fly/domain-list-community.git

      - name: Copy and Extract
        run: |
          cd $GITHUB_WORKSPACE
          cp my-extra.txt domain-list-community/data/
          cp extract.sh domain-list-community/data/
          cd domain-list-community/data
          bash extract.sh

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          files: |
            domain-list-community/data/cn-domain.txt
            domain-list-community/data/cn-domain-agh.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
