name: Build geosite.dat
on:
  workflow_dispatch:
  schedule:
    - cron: "00 00 * * 5"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Compare latest tags and set variables
        run: |
          set -x
          upstreamLatestTag=$(curl -sSL --connect-timeout 5 -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/v2fly/domain-list-community/releases/latest | grep "tag_name" | cut -d\" -f4)
          thisLatestTag=$(curl -sSL --connect-timeout 5 -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/releases/latest | grep "tag_name" | cut -d\" -f4)
          if [[ "X"$upstreamLatestTag != "X"$thisLatestTag ]]; then
            echo "NeedToSync=true" >> $GITHUB_ENV
          fi
          echo "RELEASE_NAME=$upstreamLatestTag" >> $GITHUB_ENV
          echo "TAG_NAME=$upstreamLatestTag" >> $GITHUB_ENV

        shell: bash

      - name: Checkout codebase
        uses: actions/checkout@v3
        if: ${{ env.NeedToSync }}

      - name: Clone v2fly/domain-list-community
        if: ${{ env.NeedToSync }}
        run: |
          git clone --depth=1 -b ${{ env.TAG_NAME }} https://github.com/v2fly/domain-list-community.git

      - name: Copy and Extract
        if: ${{ env.NeedToSync }}
        run: |
          cp my-extra.txt domain-list-community/data/
          cp extract.sh domain-list-community/data/
          cd domain-list-community/data
          bash extract.sh
          ls -l cn-domain*

      - name: Release
        if: ${{ env.NeedToSync }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          files: |
            domain-list-community/data/cn-domain.txt
            domain-list-community/data/cn-domain-agh.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
